from flask import Flask, render_template, request, redirect, url_for
import logging
import threading
import time
from datetime import datetime

app = Flask(__name__)

# Configure logging
logging.basicConfig(
    level=logging.DEBUG, 
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("debug.log"),
        logging.StreamHandler()
    ]
)

def log_time():
    while True:
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        app.logger.info(f"This is Appp log and Current time is {current_time}")
        time.sleep(30)

# Start the logging thread
log_thread = threading.Thread(target=log_time)
log_thread.daemon = True
log_thread.start()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/log', methods=['POST'])
def log():
    log_type = request.form['log_type']
    if log_type == 'info':
        app.logger.info('This is an info message button logs generated by user ')
    elif log_type == 'error':
        app.logger.error('This is an error message button logs generated by user')
    elif log_type == 'warn':
        app.logger.warning('This is a warning message button logs generated by user')
    elif log_type == 'debug':
        app.logger.debug('This is a debug message button logs generated by user')
    return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(host='0.0.0.0')
